# Generated by Django 2.0.4 on 2018-04-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('blogpost', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=100)),
                ('question', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
